# Generated by Django 4.2.3 on 2023-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="Dennis", max_length=50)),
                ("last_name", models.CharField(default="Akagha", max_length=50)),
                (
                    "address",
                    models.CharField(
                        default="No, 1 awoyemi street, ago palace way, okota",
                        max_length=256,
                    ),
                ),
                ("age", models.IntegerField(default=18)),
            ],
        ),
    ]
